import * as THREE from 'three';

export const ENVIRONMENT_MODES=Object.freeze({solid:'纯色',sky:'晴天',rain:'雨天',night:'夜间'});
const vertexShader=`varying vec3 vDirection;void main(){vDirection=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
const fragmentShader=`
uniform float uMode;uniform float uBrightness;varying vec3 vDirection;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.)),f.x),f.y);}
float fbm(vec2 p){float value=0.,weight=.52;for(int i=0;i<5;i++){value+=noise(p)*weight;p=p*2.03+vec2(3.1,1.7);weight*=.5;}return value;}
void main(){vec3 d=normalize(vDirection);float elevation=clamp(d.y*.5+.5,0.,1.);float skyHeight=clamp((elevation-.48)*1.92,0.,1.);vec3 day=mix(vec3(.12,.42,.74),vec3(.008,.08,.38),pow(skyHeight,.62));vec3 rain=mix(vec3(.48,.54,.58),vec3(.16,.21,.26),pow(skyHeight,.72));vec3 night=mix(vec3(.025,.05,.085),vec3(.003,.009,.026),pow(skyHeight,.55));vec2 uv=vec2(atan(d.z,d.x)*1.55,elevation*7.2);float cloudNoise=fbm(uv+vec2(2.7,7.1))*.72+fbm(uv*2.1-vec2(4.3,1.2))*.28;float cloudBand=smoothstep(.36,.47,elevation)*(1.-smoothstep(.72,.88,elevation));float clouds=smoothstep(.46,.53,cloudNoise+(0.60-elevation)*.08)*cloudBand;float wisps=smoothstep(.50,.59,fbm(uv*2.05+vec2(-1.7,.8)))*cloudBand;vec3 sunDirection=normalize(vec3(-.45,.30,-.64));float sunDot=max(dot(d,sunDirection),0.);float sunCore=pow(sunDot,420.),sunGlow=pow(sunDot,24.)*.30;vec3 sky=uMode<.5?day:(uMode<1.5?rain:night);if(uMode<.5){float haze=1.-smoothstep(.47,.55,elevation);sky=mix(sky,vec3(.82,.90,.96),haze*.14);sky=mix(sky,vec3(.985,.99,1.),clamp(clouds*.82+wisps*.16,0.,.86));sky+=vec3(1.,.80,.49)*(sunCore*1.25+sunGlow);}else if(uMode<1.5)sky=mix(sky,vec3(.66,.69,.71),clouds*.5);else{float stars=step(.9975,hash(floor(uv*38.)))*smoothstep(.56,.78,elevation);sky+=vec3(.62,.74,1.)*stars*.55;}gl_FragColor=vec4(sky*uBrightness,1.);}`;

export class DroneEnvironmentController{
  constructor(scene,{groundY=-.045}={}){
    this.scene=scene;this.groundY=groundY;this.environmentRoot=new THREE.Group();this.environmentRoot.name='EnvironmentRoot';this.lightingRoot=new THREE.Group();this.lightingRoot.name='LightingRoot';scene.add(this.environmentRoot,this.lightingRoot);
    this.sky=new THREE.Mesh(new THREE.SphereGeometry(18,24,12),new THREE.ShaderMaterial({vertexShader,fragmentShader,uniforms:{uMode:{value:0},uBrightness:{value:1}},side:THREE.BackSide,depthWrite:false,toneMapped:false}));this.sky.name='ProceduralSky';this.environmentRoot.add(this.sky);
    this.floorMaterial=new THREE.MeshStandardMaterial({color:'#e4e9ed',roughness:.9});this.shadowMaterial=new THREE.ShadowMaterial({color:0x000000,opacity:.22});this.floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),this.floorMaterial);this.floor.name='EnvironmentFloor';this.floor.rotation.x=-Math.PI/2;this.floor.position.y=groundY;this.floor.receiveShadow=true;this.environmentRoot.add(this.floor);
    this.hemi=new THREE.HemisphereLight(0xffffff,0x657080,1.7);this.key=new THREE.DirectionalLight(0xfffaf1,3);this.fill=new THREE.DirectionalLight(0xddeaff,1.5);this.key.position.set(-3,5,-4);this.key.castShadow=true;this.key.shadow.mapSize.set(1024,1024);Object.assign(this.key.shadow.camera,{left:-.6,right:.6,top:.6,bottom:-.6,near:.01,far:8});this.key.shadow.bias=-.00005;this.fill.position.set(.8,.6,.7);this.lightingRoot.add(this.hemi,this.key,this.fill);
    this.groundWorld=null;this.rainLayer=null;this.loadingGround=null;this.loadingRain=null;this.config={mode:'solid',color:'#edf0f2',groundVisible:true,flightRoute:false,cameraFollow:false,brightness:1,groundIntensity:.58,rainAmount:.65,fog:0};this.applyConfig(this.config);
  }
  async ensureGroundWorld(){if(this.groundWorld)return this.groundWorld;if(!this.loadingGround)this.loadingGround=import('../../environment/GroundWorld.js').then(({GroundWorld})=>{this.groundWorld=new GroundWorld({groundY:this.groundY-1.6});this.environmentRoot.add(this.groundWorld.root);return this.groundWorld;});return this.loadingGround;}
  async ensureRain(){if(this.rainLayer)return this.rainLayer;if(!this.loadingRain)this.loadingRain=import('../../environment/RainLayer.js').then(({RainLayer})=>{this.rainLayer=new RainLayer();this.environmentRoot.add(this.rainLayer.points);return this.rainLayer;});return this.loadingRain;}
  applyLighting(mode){const presets={solid:[1.7,3,1.5],sky:[1.45,2.65,1.15],rain:[.82,1.3,.55],night:[.28,.72,.34]},values=presets[mode]||presets.solid,scale=this.config.brightness;[this.hemi.intensity,this.key.intensity,this.fill.intensity]=values.map(value=>value*scale);this.hemi.color.set(mode==='night'?0x6688bb:0xffffff);this.key.color.set(mode==='night'?0xa9c5ff:0xfffaf1);}
  async applyConfig(update={}){
    const revision=(this.revision??0)+1;this.revision=revision;Object.assign(this.config,update);if(this.config.mode==='transparent')this.config.mode='solid';const {mode,color}=this.config,natural=mode!=='solid';
    if(natural){const ground=await this.ensureGroundWorld();if(revision!==this.revision)return this.getConfig();ground.setVisible(this.config.groundVisible!==false);ground.applyPreset(mode,this.config.groundIntensity);}else this.groundWorld?.setVisible(false);
    if(mode==='rain'){const rain=await this.ensureRain();rain.points.visible=this.config.rainAmount>0;rain.setAmount(this.config.rainAmount);}else if(this.rainLayer){this.rainLayer.dispose();this.rainLayer=null;this.loadingRain=null;}
    this.sky.visible=natural;this.sky.material.uniforms.uMode.value=mode==='rain'?1:mode==='night'?2:0;this.sky.material.uniforms.uBrightness.value=.65+this.config.brightness*.35;this.floor.material=mode==='solid'?this.floorMaterial:this.shadowMaterial;this.floorMaterial.color.set(color);this.scene.background=natural?null:new THREE.Color(color);
    const fogAmount=THREE.MathUtils.clamp(this.config.fog,0,1);this.scene.fog=fogAmount===0?null:mode==='rain'?new THREE.FogExp2('#46535b',.008+fogAmount*.072):mode==='sky'?new THREE.Fog('#91b9d3',8-fogAmount*2,22-fogAmount*4):mode==='night'?new THREE.Fog('#07101d',6-fogAmount*2,18-fogAmount*4):null;this.applyLighting(mode);return this.getConfig();
  }
  prepareExport({transparent=false,includeRain=true}={}){const saved={background:this.scene.background,fog:this.scene.fog,sky:this.sky.visible,rain:this.rainLayer?.points.visible,ground:this.groundWorld?.root.visible,floor:this.floor.material};if(transparent){this.scene.background=null;this.scene.fog=null;this.sky.visible=false;if(this.groundWorld)this.groundWorld.root.visible=false;this.floor.material=this.shadowMaterial;}if(!includeRain&&this.rainLayer)this.rainLayer.points.visible=false;return()=>{this.scene.background=saved.background;this.scene.fog=saved.fog;this.sky.visible=saved.sky;if(this.rainLayer&&saved.rain!==undefined)this.rainLayer.points.visible=saved.rain;if(this.groundWorld&&saved.ground!==undefined)this.groundWorld.root.visible=saved.ground;this.floor.material=saved.floor;};}
  update(delta){if(this.rainLayer?.points.visible)this.rainLayer.update(delta);}
  getGroundSurfaceYAt(x,z){return this.groundWorld?.getSurfaceYAt(x,z)??this.groundY;}
  getStats(){return{groundWorld:this.groundWorld?.getStats()??null,rainPoints:this.rainLayer?.geometry.drawRange.count??0};}
  getConfig(){return structuredClone(this.config);}
  dispose(){this.environmentRoot.removeFromParent();this.lightingRoot.removeFromParent();this.groundWorld?.dispose();this.rainLayer?.dispose();this.sky.geometry.dispose();this.sky.material.dispose();this.floor.geometry.dispose();this.floorMaterial.dispose();this.shadowMaterial.dispose();}
}
