import * as THREE from 'three';

const COLORS={sky:{ground:0x69766d,road:0x3f494d,marking:0xc7c5b6,building:0x7d8789,tree:0x496c56,window:0xf6c879},rain:{ground:0x4c5853,road:0x343e42,marking:0x87908d,building:0x646f73,tree:0x395247,window:0xcbb479},night:{ground:0x142522,road:0x11191d,marking:0x405056,building:0x25313a,tree:0x122b22,window:0xffbd63}};
const ROAD_LINES=[[0,-6],[0,-2.5],[0,2.5],[0,6],[-6,0],[-2.5,0],[2.5,0],[6,0]];
const BLOCK_CENTERS=[-4.25,0,4.25].flatMap(x=>[-4.25,0,4.25].map(z=>[x,z])).filter(([x,z])=>x||z);
const BUILDING_SLOTS=[[-.66,-.58],[0,-.58],[.66,-.58],[-.66,.58],[0,.58],[.66,.58]];
const TREE_SLOTS=[[-1.34,-1.25],[-.67,-1.25],[.67,-1.25],[1.34,-1.25],[-1.34,0],[1.34,0],[-1.34,1.25],[0,1.25],[1.34,1.25]];

function rng(seed=31337){return()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);}
function setInstance(mesh,index,position,scale,yaw=0,flat=false){const rotation=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),yaw);if(flat)rotation.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),-Math.PI/2));mesh.setMatrixAt(index,new THREE.Matrix4().compose(position,rotation,scale));}

/** Low-altitude context built as a coherent street grid. No external assets. */
export class GroundWorld{
  constructor({groundY=-1.65}={}){
    this.root=new THREE.Group();this.root.name='GroundWorld';this.root.position.y=groundY;this.materials=[];this.geometries=[];this.instances=[];this.maxObstacleLocalY=0;const random=rng();

    const terrainGeometry=new THREE.PlaneGeometry(24,24,28,28),position=terrainGeometry.attributes.position;
    for(let index=0;index<position.count;index++){const x=position.getX(index),y=position.getY(index);position.setZ(index,.012*Math.sin(x*.55)*Math.cos(y*.48)+.006*Math.sin((x+y)*1.2));}
    terrainGeometry.computeVertexNormals();const terrainMaterial=new THREE.MeshStandardMaterial({color:COLORS.sky.ground,roughness:1}),terrain=new THREE.Mesh(terrainGeometry,terrainMaterial);terrain.name='Terrain';terrain.rotation.x=-Math.PI/2;terrain.receiveShadow=true;this.root.add(terrain);this.terrain=terrain;this.geometries.push(terrainGeometry);this.materials.push(terrainMaterial);

    const roadGeometry=new THREE.PlaneGeometry(1,1),roadMaterial=new THREE.MeshStandardMaterial({color:COLORS.sky.road,roughness:1,polygonOffset:true,polygonOffsetFactor:-2}),roads=new THREE.InstancedMesh(roadGeometry,roadMaterial,8);roads.name='RoadGrid';
    const markingGeometry=new THREE.PlaneGeometry(1,1),markingMaterial=new THREE.MeshBasicMaterial({color:COLORS.sky.marking,transparent:true,opacity:.42}),markings=new THREE.InstancedMesh(markingGeometry,markingMaterial,8);markings.name='RoadCenterLines';
    ROAD_LINES.forEach(([x,z],index)=>{const vertical=index>=4,yaw=vertical?Math.PI/2:0;setInstance(roads,index,new THREE.Vector3(x,.018,z),new THREE.Vector3(24,.34,1),yaw,true);setInstance(markings,index,new THREE.Vector3(x,.023,z),new THREE.Vector3(24,.018,1),yaw,true);});roads.instanceMatrix.needsUpdate=true;markings.instanceMatrix.needsUpdate=true;this.root.add(roads,markings);this.roads=roads;this.markings=markings;this.geometries.push(roadGeometry,markingGeometry);this.materials.push(roadMaterial,markingMaterial);this.instances.push(roads,markings);

    const blockGeometry=new THREE.BoxGeometry(1,1,1),blockMaterial=new THREE.MeshStandardMaterial({color:0x929c96,roughness:1}),blocks=new THREE.InstancedMesh(blockGeometry,blockMaterial,BLOCK_CENTERS.length);blocks.name='SidewalkBlocks';BLOCK_CENTERS.forEach(([x,z],index)=>setInstance(blocks,index,new THREE.Vector3(x,.025,z),new THREE.Vector3(3.05,.05,2.95)));blocks.instanceMatrix.needsUpdate=true;blocks.receiveShadow=true;this.root.add(blocks);this.blocks=blocks;this.geometries.push(blockGeometry);this.materials.push(blockMaterial);this.instances.push(blocks);

    const roofGeometry=new THREE.BoxGeometry(1,1,1),roofMaterial=new THREE.MeshStandardMaterial({color:0x4e595c,roughness:.86}),roofs=new THREE.InstancedMesh(roofGeometry,roofMaterial,48);roofs.name='RooftopCaps';
    const buildingTypes=[[.42,.48,.38],[.5,.78,.42],[.34,.36,.34],[.55,.58,.46]],windowSites=[];this.buildings=buildingTypes.map((_,type)=>{const geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshStandardMaterial({color:COLORS.sky.building,roughness:.9,metalness:.02}),mesh=new THREE.InstancedMesh(geometry,material,12);mesh.name=`Buildings_${type+1}`;mesh.castShadow=true;mesh.receiveShadow=true;this.root.add(mesh);this.geometries.push(geometry);this.materials.push(material);this.instances.push(mesh);return mesh;});
    const typeCounts=[0,0,0,0];let buildingIndex=0;
    BLOCK_CENTERS.forEach(([centerX,centerZ])=>BUILDING_SLOTS.forEach(([offsetX,offsetZ])=>{const type=buildingIndex%4,instanceIndex=typeCounts[type]++,[baseWidth,baseHeight,baseDepth]=buildingTypes[type],width=baseWidth*(.82+random()*.34),depth=baseDepth*(.82+random()*.34),height=baseHeight*(.72+random()*.62),x=centerX+offsetX,z=centerZ+offsetZ,yaw=(random()-.5)*.08;this.maxObstacleLocalY=Math.max(this.maxObstacleLocalY,.093+height);setInstance(this.buildings[type],instanceIndex,new THREE.Vector3(x,.05+height/2,z),new THREE.Vector3(width,height,depth),yaw);setInstance(roofs,buildingIndex,new THREE.Vector3(x,.058+height,z),new THREE.Vector3(width*.72,.035,depth*.72),yaw);this.buildings[type].setColorAt(instanceIndex,new THREE.Color(COLORS.sky.building).multiplyScalar(.88+random()*.16));if(buildingIndex%4===0){const inward=new THREE.Vector3(-x,0,-z).normalize(),face= Math.abs(inward.x)>Math.abs(inward.z)?width/2:depth/2;windowSites.push({position:new THREE.Vector3(x+inward.x*(face+.008),.05+height*.57,z+inward.z*(face+.008)),yaw:Math.atan2(inward.x,inward.z)});}buildingIndex++;}));
    for(const mesh of this.buildings){mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;}
    roofs.instanceMatrix.needsUpdate=true;roofs.castShadow=true;roofs.receiveShadow=true;this.root.add(roofs);this.roofs=roofs;this.geometries.push(roofGeometry);this.materials.push(roofMaterial);this.instances.push(roofs);

    const trunkGeometry=new THREE.CylinderGeometry(.035,.052,.27,5),trunkMaterial=new THREE.MeshStandardMaterial({color:0x463a30,roughness:1}),trunks=new THREE.InstancedMesh(trunkGeometry,trunkMaterial,72),crownGeometry=new THREE.IcosahedronGeometry(.17,0),crownMaterial=new THREE.MeshStandardMaterial({color:COLORS.sky.tree,roughness:1}),crowns=new THREE.InstancedMesh(crownGeometry,crownMaterial,72);trunks.name='TreeTrunks';crowns.name='TreeCrowns';let treeIndex=0;BLOCK_CENTERS.forEach(([centerX,centerZ])=>TREE_SLOTS.forEach(([offsetX,offsetZ])=>{const scale=.78+random()*.42,x=centerX+offsetX,z=centerZ+offsetZ;setInstance(trunks,treeIndex,new THREE.Vector3(x,.05+.135*scale,z),new THREE.Vector3(scale,scale,scale));setInstance(crowns,treeIndex,new THREE.Vector3(x,.05+.37*scale,z),new THREE.Vector3(scale,scale,scale),random()*Math.PI);treeIndex++;}));trunks.instanceMatrix.needsUpdate=true;crowns.instanceMatrix.needsUpdate=true;this.root.add(trunks,crowns);this.crowns=crowns;this.geometries.push(trunkGeometry,crownGeometry);this.materials.push(trunkMaterial,crownMaterial);this.instances.push(trunks,crowns);

    const windowGeometry=new THREE.PlaneGeometry(.12,.14),windowMaterial=new THREE.MeshBasicMaterial({color:COLORS.night.window,transparent:true,opacity:0,side:THREE.DoubleSide,toneMapped:false}),windows=new THREE.InstancedMesh(windowGeometry,windowMaterial,windowSites.length);windows.name='WarmWindowHints';windowSites.forEach((site,index)=>setInstance(windows,index,site.position,new THREE.Vector3(1,1,1),site.yaw));windows.instanceMatrix.needsUpdate=true;this.root.add(windows);this.windows=windows;this.geometries.push(windowGeometry);this.materials.push(windowMaterial);this.instances.push(windows);
    this.applyPreset('sky',.58);this.root.visible=false;
  }
  applyPreset(mode='sky',intensity=.58){const palette=COLORS[mode]||COLORS.sky,value=THREE.MathUtils.clamp(Number(intensity),0,1);this.terrain.material.color.setHex(palette.ground).multiplyScalar(.58+value*.58);this.roads.material.color.setHex(palette.road);this.markings.material.color.setHex(palette.marking);this.markings.material.opacity=mode==='night'?.28:.42;this.blocks.material.color.setHex(mode==='night'?0x23302f:mode==='rain'?0x68736f:0x929c96);this.roofs.material.color.setHex(mode==='night'?0x151e24:mode==='rain'?0x424d51:0x4e595c);this.crowns.material.color.setHex(palette.tree);for(const mesh of this.buildings)mesh.material.color.setHex(palette.building).multiplyScalar(.68+value*.4);this.windows.material.color.setHex(palette.window);this.windows.material.opacity=mode==='night'?.68:0;this.windows.visible=mode==='night';}
  setVisible(visible){this.root.visible=Boolean(visible);}
  getSurfaceYAt(x,z){this.root.updateWorldMatrix(true,true);const raycaster=new THREE.Raycaster(new THREE.Vector3(x,this.root.position.y+10,z),new THREE.Vector3(0,-1,0),0,20),hits=raycaster.intersectObjects([this.terrain,this.roads,this.blocks],false);return hits[0]?.point.y??this.root.position.y;}
  getMaxObstacleY(){return this.root.position.y+this.maxObstacleLocalY;}
  getStats(){let triangles=(this.terrain.geometry.index?.count??this.terrain.geometry.attributes.position.count)/3;for(const mesh of this.instances)triangles+=((mesh.geometry.index?.count??mesh.geometry.attributes.position.count)/3)*mesh.count;return{drawCalls:1+this.instances.length,triangles,buildings:48,trees:72,roads:8};}
  dispose(){this.root.removeFromParent();for(const geometry of this.geometries)geometry.dispose();for(const material of this.materials)material.dispose();}
}
