import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {ModelSession,GENERIC_CAPABILITIES} from '../model/ModelSession.js';
import {getLocale,setLocale,t} from '../i18n/index.js';
import {DroneHoverController} from './effects/DroneHoverController.js';
import {FlightRouteController} from '../environment/FlightRouteController.js';

test('generic GLB session preserves source transforms and scale while centering only its wrapper',()=>{const source=new THREE.Group(),mesh=new THREE.Mesh(new THREE.BoxGeometry(2,4,6),new THREE.MeshBasicMaterial());source.position.set(5,2,-3);source.scale.set(2,2,2);source.add(mesh);const before={position:source.position.clone(),scale:source.scale.clone()};const session=ModelSession.inspectGLTF({scene:source,animations:[]},{fileName:'test.glb'});assert.deepEqual(source.position.toArray(),before.position.toArray());assert.deepEqual(source.scale.toArray(),before.scale.toArray());assert.notEqual(session.sceneRoot.position.length(),0);assert.equal(session.sourceType,'generic-imported');assert.deepEqual(session.capabilities,GENERIC_CAPABILITIES);assert.equal(session.metrics.meshes,1);session.dispose();});
test('lightweight i18n switches semantic keys with fallback',()=>{const previous=getLocale();setLocale('en-US');assert.equal(t('model.upload'),'Upload GLB');setLocale('invalid');assert.equal(t('model.upload'),'上传 GLB');setLocale(previous);});
test('hover switch creates visible motion and returns exactly to rest',()=>{const root=new THREE.Group(),hover=new DroneHoverController(root);hover.setConfig({enabled:true,amplitude:.024,speed:.5});for(let i=0;i<80;i++)hover.update(.02,.5+i*.02);assert.ok(Math.abs(root.position.y)>.005);hover.setConfig({enabled:false});for(let i=0;i<100;i++)hover.update(.02,3+i*.02);assert.ok(Math.abs(root.position.y)<.0001);});
test('flight route is map-scale, straight, longer than one minute and lands on resolved ground',()=>{const parent=new THREE.Group(),model=new THREE.Mesh(new THREE.BoxGeometry(.6,.2,.6),new THREE.MeshBasicMaterial());model.position.set(1,2,3);parent.add(model);const route=new FlightRouteController(parent,{groundResolver:()=>-1.62});route.bind(model);route.setEnabled(true);assert.equal(route.root.visible,true);assert.ok(route.duration>60);const box=new THREE.Box3().setFromObject(model,true);assert.ok(Math.abs(box.min.y-(route.groundY+.003))<1e-6);for(let i=1;i<route.cruisePoints.length;i++){const a=route.cruisePoints[i-1],b=route.cruisePoints[i];assert.ok(a.x===b.x||a.z===b.z);assert.equal(a.y,b.y);assert.ok([2.5,6].includes(Math.abs(a.x))||[2.5,6].includes(Math.abs(a.z)));}assert.ok(new THREE.Box3().setFromPoints(route.cruisePoints).getSize(new THREE.Vector3()).x>=12);for(let i=0;i<Math.round(route.duration/.05);i++)route.update(.05);const landed=new THREE.Box3().setFromObject(model,true);assert.ok(Math.abs(landed.min.y-(route.groundY+.003))<1e-5);route.setEnabled(false);assert.deepEqual(model.position.toArray(),[1,2,3]);route.dispose();model.geometry.dispose();model.material.dispose();assert.equal(route.root.parent,null);});
