import {MAPPING_ROLES,createMappedProfile,downloadProfile,embedProfileMetadata,listMappableObjects,suggestMappings,validateMappings} from './ModelProfileMapper.js';

export class ModelMappingDialog{
  constructor(dialog,{translate,onApply}){this.dialog=dialog;this.t=translate;this.onApply=onApply;dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('[data-auto]').onclick=()=>this.fill(suggestMappings(this.objects));dialog.querySelector('[data-save]').onclick=()=>this.save();}
  open(session){this.session=session;this.objects=listMappableObjects(session.modelRoot);const base=session.fileName.replace(/\.glb$/i,'').replace(/[^a-z0-9._-]+/gi,'-').toLowerCase()||'custom-drone';this.dialog.querySelector('[name=profile-id]').value=`community.${base}`;this.dialog.querySelector('[name=profile-label]').value=session.fileName.replace(/\.glb$/i,'');this.render();this.fill(session.profile?.roles??suggestMappings(this.objects));this.setMessage('');this.dialog.showModal();}
  render(){const safe=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const options=this.objects.map(item=>`<option value="${safe(item.name)}">${safe(item.name)} · ${safe(item.type)}</option>`).join('');this.dialog.querySelector('.mapping-roles').innerHTML=MAPPING_ROLES.map(role=>`<label><span>${role.key}${role.required?' *':''}</span><select data-role="${role.key}" ${role.multiple?'multiple size="3"':''}><option value="">—</option>${options}</select></label>`).join('');}
  fill(mappings){for(const select of this.dialog.querySelectorAll('[data-role]')){const values=new Set(mappings[select.dataset.role]??[]);for(const option of select.options)option.selected=values.has(option.value);}}
  read(){return Object.fromEntries([...this.dialog.querySelectorAll('[data-role]')].map(select=>[select.dataset.role,[...select.selectedOptions].map(option=>option.value).filter(Boolean)]));}
  setMessage(text,error=false){const node=this.dialog.querySelector('.mapping-message');node.textContent=text;node.classList.toggle('error',error);}
  save(){const mappings=this.read(),check=validateMappings(mappings);if(!check.valid){this.setMessage(check.errors.map(item=>item.message).join(' · '),true);return;}try{const profile=createMappedProfile({id:this.dialog.querySelector('[name=profile-id]').value.trim(),label:this.dialog.querySelector('[name=profile-label]').value.trim(),forwardAxis:this.dialog.querySelector('[name=forward-axis]').value,mappings});if(!/^[a-z0-9][a-z0-9._-]+$/.test(profile.id))throw new Error('Profile id must use lowercase letters, numbers, dots, underscores, or hyphens');embedProfileMetadata(this.session.modelRoot,profile);this.session.profile=profile;this.session.sourceType='profile-mapped';this.onApply?.(profile);downloadProfile(profile,`${this.session.fileName.replace(/\.glb$/i,'')}.aerometric.json`);this.dialog.close();}catch(error){this.setMessage(error.message,true);}}
}
