import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {assessScene} from '../../validator/src/rules.mjs';
import './style.css';

const app=document.querySelector('#app');
app.innerHTML=`<header><a href="#">◇ AEROMETRIC</a><span>WEB VALIDATOR · 0.1</span></header><section class="intro"><p>MODEL STANDARD / LOCAL VALIDATION</p><h1>验证无人机模型，<br>文件留在你的浏览器。</h1><p class="lead">拖入一个 GLB，可选配套的 <code>.aerometric.json</code>。检查解析、结构映射、能力声明、面数与文件体积。</p></section><section id="drop" class="drop"><input id="files" type="file" accept=".glb,.json,model/gltf-binary,application/json" multiple hidden><button id="choose">选择 GLB + Profile</button><p>或将文件拖到这里</p><small>文件仅在当前页面内解析，不会上传。</small></section><section id="selection" class="selection"><div><span>GLB</span><strong id="glb-name">未选择</strong></div><div><span>PROFILE</span><strong id="profile-name">可选</strong></div><button id="clear">清除</button></section><section id="result" class="result empty"><div class="result-head"><div><span id="mark">—</span><div><small>VALIDATION RESULT</small><h2 id="status">等待模型</h2></div></div><strong id="level">LEVEL —</strong></div><div id="metrics" class="metrics"></div><div class="columns"><article><h3>错误 <b id="error-count">0</b></h3><div id="errors" class="issues"><p>尚未运行。</p></div></article><article><h3>建议 <b id="warning-count">0</b></h3><div id="warnings" class="issues"><p>尚未运行。</p></div></article></div></section><footer>AEROMETRIC MODEL STANDARD · CLIENT-SIDE VALIDATOR</footer>`;

const $=selector=>document.querySelector(selector),drop=$('#drop'),input=$('#files');let glbFile=null,profileFile=null,runId=0;
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const size=bytes=>bytes>1024*1024?`${(bytes/1024/1024).toFixed(2)} MB`:`${(bytes/1024).toFixed(0)} KB`;

function issueList(target,items,empty){target.innerHTML=items.length?items.map(item=>`<div><code>${escape(item.code)}</code><p>${escape(item.message)}</p></div>`).join(''):`<p>${empty}</p>`;}
function render(report){const result=$('#result');result.className=`result ${report.pass?'pass':'fail'}`;$('#mark').textContent=report.pass?'✓':'×';$('#status').textContent=report.pass?'验证通过':'需要修正';$('#level').textContent=`LEVEL ${report.level}`;$('#error-count').textContent=report.errors.length;$('#warning-count').textContent=report.warnings.length;const m=report.metrics;$('#metrics').innerHTML=[['文件',size(m.bytes)],['对象',m.objects],['网格',m.meshes],['三角面',m.triangles.toLocaleString()],['材质',m.materials],['动画',m.animations]].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('');issueList($('#errors'),report.errors,'没有阻塞问题。');issueList($('#warnings'),report.warnings,'没有额外建议。');}
function renderFailure(error){render({pass:false,level:'—',metrics:{bytes:glbFile?.size??0,objects:0,meshes:0,triangles:0,materials:0,animations:0},errors:[{code:'PARSE',message:error.message}],warnings:[]});}
async function validate(){const id=++runId;$('#glb-name').textContent=glbFile?.name??'未选择';$('#profile-name').textContent=profileFile?.name??'可选';if(!glbFile){$('#result').className='result empty';$('#status').textContent='等待模型';$('#level').textContent='LEVEL —';return;}$('#status').textContent='正在解析';try{const [buffer,profileText]=await Promise.all([glbFile.arrayBuffer(),profileFile?.text()]);const profile=profileText?JSON.parse(profileText):null;const gltf=await new GLTFLoader().parseAsync(buffer,'');if(id!==runId)return;render(assessScene(gltf.scene,glbFile.size,{profile,animations:gltf.animations.length}));}catch(error){if(id===runId)renderFailure(error);}}
function accept(files){for(const file of files){const name=file.name.toLowerCase();if(name.endsWith('.glb'))glbFile=file;else if(name.endsWith('.aerometric.json')||name.endsWith('.json'))profileFile=file;}validate();}
$('#choose').onclick=()=>input.click();input.onchange=()=>{accept(input.files);input.value='';};$('#clear').onclick=()=>{glbFile=profileFile=null;runId++;$('#glb-name').textContent='未选择';$('#profile-name').textContent='可选';$('#result').className='result empty';$('#status').textContent='等待模型';$('#level').textContent='LEVEL —';$('#metrics').innerHTML='';issueList($('#errors'),[],'尚未运行。');issueList($('#warnings'),[],'尚未运行。');};
for(const type of ['dragenter','dragover'])drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add('active');});for(const type of ['dragleave','drop'])drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('active');});drop.addEventListener('drop',event=>accept(event.dataTransfer.files));
