import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {gzipSync} from 'node:zlib';

const chrome='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',port=9600+Math.floor(Math.random()*200),profile=path.join(os.tmpdir(),`aerometric-v31-${Date.now()}`),base=process.env.V31_AUDIT_URL||'http://127.0.0.1:4173/',reviewDir=path.resolve('blender_drone/v3/platform/v31-review');
if(!fs.existsSync(chrome))throw new Error('Chrome not found');fs.mkdirSync(reviewDir,{recursive:true});const browser=spawn(chrome,[`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--headless=new','--no-first-run','--hide-scrollbars','--window-size=1440,900',base],{stdio:'ignore'}),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function endpoint(){for(let i=0;i<100;i++){try{const pages=await fetch(`http://127.0.0.1:${port}/json/list`).then(response=>response.json()),page=pages.find(item=>item.type==='page'&&item.url.startsWith(base));if(page?.webSocketDebuggerUrl)return page.webSocketDebuggerUrl;}catch{}await wait(100);}throw new Error('Chrome DevTools endpoint unavailable');}
let id=0;const pending=new Map();
try{
  const socket=new WebSocket(await endpoint());await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});socket.onmessage=event=>{const message=JSON.parse(event.data),entry=pending.get(message.id);if(entry){pending.delete(message.id);message.error?entry.reject(new Error(message.error.message)):entry.resolve(message.result);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const callId=++id;pending.set(callId,{resolve,reject});socket.send(JSON.stringify({id:callId,method,params}));});await send('Runtime.enable');await send('Page.enable');
  for(let i=0;i<120;i++){const ready=await send('Runtime.evaluate',{expression:'Boolean(window.__DRONE_DEMO__?.renderer)',returnByValue:true});if(ready.result.value)break;if(i===119)throw new Error('viewer did not initialize');await wait(100);}
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;};
  const initialResources=await evaluate(`performance.getEntriesByType('resource').map(r=>({name:new URL(r.name).pathname,transferSize:r.transferSize,encodedBodySize:r.encodedBodySize,duration:Number(r.duration.toFixed(1))}))`);
  async function measure(mode){return evaluate(`(async()=>{await window.__DRONE_DEMO__.setEnvironment({mode:${JSON.stringify(mode)}});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const start=performance.now();let frames=0;await new Promise(resolve=>{function frame(now){frames++;if(now-start>=1200)resolve();else requestAnimationFrame(frame);}requestAnimationFrame(frame);});const elapsed=performance.now()-start,r=window.__DRONE_DEMO__.renderer.info;return{mode:${JSON.stringify(mode)},fps:Number((frames*1000/elapsed).toFixed(1)),drawCalls:r.render.calls,triangles:r.render.triangles,geometries:r.memory.geometries,textures:r.memory.textures,environment:window.__DRONE_DEMO__.environmentController.getStats()};})()`);}
  const modes=[];for(const mode of ['sky','rain','night']){modes.push(await measure(mode));const capture=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(reviewDir,`v31-${mode}.png`),Buffer.from(capture.data,'base64'));}const memoryBefore=await evaluate(`({...window.__DRONE_DEMO__.renderer.info.memory})`);for(let i=0;i<3;i++){await evaluate(`window.__DRONE_DEMO__.setEnvironment({mode:'rain'})`);await evaluate(`window.__DRONE_DEMO__.setEnvironment({mode:'night'})`);}const memoryAfter=await evaluate(`({...window.__DRONE_DEMO__.renderer.info.memory})`);
  const buildFiles=fs.readdirSync('dist/assets').map(name=>{const bytes=fs.readFileSync(path.join('dist/assets',name));return{name,bytes:bytes.length,gzipBytes:gzipSync(bytes).length};}),initialBuild=buildFiles.filter(file=>/^index-/.test(file.name)||file.name.startsWith('StatusLightBloom-')),initialGzip=initialBuild.reduce((sum,file)=>sum+file.gzipBytes,0)+gzipSync(fs.readFileSync('dist/index.html')).length;
  const report={generatedAt:new Date().toISOString(),budgets:{initialGzipMax:1200000,environmentTrianglesMax:30000,groundWorldDrawCallsMax:15,defaultDrawCallsMax:100,targetFps:50},build:{initialGzipBytes:initialGzip,withinBudget:initialGzip<=1200000,files:buildFiles},initialResources,modes,memorySwitch:{before:memoryBefore,after:memoryAfter,stable:memoryAfter.geometries<=memoryBefore.geometries&&memoryAfter.textures<=memoryBefore.textures},notes:['FPS is a headless Chrome sample on this machine, not a cross-device guarantee.','renderer.info reflects the final composed pass; GroundWorld reports its deterministic draw-call and triangle budgets separately.']};fs.writeFileSync(path.join(reviewDir,'audit-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));socket.close();
}finally{browser.kill();try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:3,retryDelay:100});}catch{}}
