export default {
  'app.version':'V3.2.1','app.console':'Controls','app.loading':'Loading','app.ready':'Ready','app.loadFailed':'Load failed',
  'model.current':'Current model','model.preset':'Preset model','model.community':'Community models','model.libraryLoading':'Loading model catalog…','model.libraryEmpty':'No licensed community models yet','model.libraryUnavailable':'Model catalog unavailable','model.local':'Local model','model.upload':'Upload GLB','model.drop':'Drop GLB to load','model.dropHint':'or drop a GLB on the viewport','model.loading':'Loading model…','model.loaded':'Model loaded','model.unable':'Unable to load this GLB','model.fileType':'Only .glb files are supported','model.large':'This model is large and may load or export slowly','model.scale':'Model scale may be unusual','model.generic':'Control profile not configured','model.mapped':'Profile mapped','model.compatible':'AEROMETRIC Compatible','model.configure':'Configure Model','model.builtIn':'Built-in model','model.meshes':'Meshes','model.triangles':'Triangles','model.materials':'Materials','model.animations':'Animations','mapping.title':'Model Mapping','mapping.note':'Mapping never renames, moves, or scales nodes. Saving downloads a Profile and embeds semantics for the current GLB export.','mapping.label':'Model label','mapping.forward':'Forward axis','mapping.auto':'Auto-map again','mapping.save':'Save & Download Profile','mapping.saved':'Profile generated. Supported mapped controls are now active.',
  'section.motion':'Motion','section.appearance':'Appearance','section.status':'Status & Effects','section.environment':'Environment','section.export':'Export','capability.partColors':'Color','capability.partVisibility':'Visibility','capability.rotorControl':'Rotors','capability.gimbalControl':'Gimbal','capability.statusLights':'Status lights','capability.statusField':'Status field','motion.rotor':'Rotor','motion.start':'Start Rotors','motion.stop':'Stop Rotors','motion.speed':'Rotor speed','motion.pose':'Pose & Gimbal','motion.pitch':'Pitch','motion.roll':'Roll','motion.yaw':'Yaw','motion.gimbalPitch':'Gimbal pitch','motion.gimbalYaw':'Gimbal yaw',
  'part.body':'Body','part.topCover':'Top Cover','part.arms':'Arms','part.rotors':'Rotors','part.motors':'Motors','part.landingGear':'Landing Gear','part.gimbal':'Gimbal','part.camera':'Camera','part.show':'Show {part}','part.color':'{part} color',
  'status.online':'Online','status.mission':'Mission','status.notice':'Caution','status.warning':'Alert','status.custom':'Custom','status.field':'Status Field','status.hover':'Hover','status.color':'Status color','status.speed':'Ripple speed','status.range':'Range','status.intensity':'Field intensity','status.lights':'Status lights','status.lightIntensity':'Light intensity',
  'environment.solid':'Solid','environment.sky':'Sunny','environment.rain':'Rain','environment.night':'Night','environment.color':'Background','environment.ground':'Ground world','environment.flightRoute':'City flight loop (76s)','environment.flightFollow':'Camera follow','environment.brightness':'Brightness','environment.groundIntensity':'Ground intensity','environment.rainAmount':'Rain amount','environment.fog':'Fog','environment.note':'Fog is fully disabled at 0; environment changes do not reload the model.',
  'camera.perspective':'Perspective','camera.product45':'Product 45°','camera.top':'Top','camera.front':'Front','camera.rear':'Rear','camera.left':'Left','camera.right':'Right','camera.focal':'Focal / perspective','camera.distance':'Dolly / framing','camera.height':'Height','camera.focus':'Focus','camera.reset':'Reset','camera.hint':'Focal length changes perspective compression · Distance changes camera position','camera.viewport':'Interactive 3D viewport',
  'export.imageTitle':'Image','export.format':'Format','export.size':'Size','export.custom':'Custom','export.width':'Width','export.height':'Height','export.transparent':'Transparent','export.rain':'Include rain','export.image':'Export Image','export.imageNote':'Offscreen scene render without page UI','export.modelTitle':'Model','export.glb':'Export Current GLB','export.glbNote':'Preserves current materials, dimensions, and visible objects','export.original':'Download Original GLB ↗','export.rendering':'Rendering {size}…','export.done':'Done · {size} · {mb} MB','export.failed':'Export failed','export.writing':'Writing current GLB…','export.glbDone':'Done · {kb} KB','reset.all':'Restore DEFAULT_DRONE_CONFIG','locale.label':'中文','common.close':'Close'
};
