export default {
  'app.noModel':'请选择模型','model.choose':'选择模型','model.emptyTitle':'开始使用 AEROMETRIC','model.emptyHint':'上传您有权使用的 GLB，或选择社区参考模型。',
  'app.version':'V3.2.1','app.console':'创作控制台','app.loading':'载入中','app.ready':'已载入','app.loadFailed':'载入失败',
  'model.official':'官方','model.current':'当前模型','model.preset':'预制模型','model.community':'社区模型','model.libraryLoading':'正在读取模型目录…','model.libraryEmpty':'暂无已授权的社区模型','model.libraryUnavailable':'模型目录暂时不可用','model.local':'本地模型','model.upload':'上传 GLB','model.drop':'释放以载入 GLB','model.dropHint':'或拖拽 GLB 到画布','model.loading':'正在载入模型…','model.loaded':'模型已载入','model.unable':'无法读取该 GLB','model.fileType':'仅支持 .glb 文件','model.large':'模型较大，加载和导出可能较慢','model.scale':'模型尺度可能异常','model.generic':'未配置控制映射','model.mapped':'Profile 已映射','model.compatible':'AEROMETRIC 兼容','model.configure':'配置模型','model.builtIn':'内置模型','model.meshes':'网格','model.triangles':'三角面','model.materials':'材质','model.animations':'动画','mapping.title':'模型映射','mapping.note':'映射不会重命名、移动或缩放节点。保存后下载 Profile，并将语义写入当前模型供 GLB 导出。','mapping.label':'模型名称','mapping.forward':'前方轴','mapping.auto':'重新自动匹配','mapping.save':'保存并下载 Profile','mapping.saved':'Profile 已生成，已启用当前模型支持的映射控制。',
  'section.motion':'运动','section.appearance':'外观','section.status':'状态与特效','section.environment':'环境','section.export':'导出','capability.partColors':'换色','capability.partVisibility':'显隐','capability.rotorControl':'旋翼','capability.gimbalControl':'云台','capability.statusLights':'状态灯','capability.statusField':'状态场','motion.rotor':'旋翼','motion.start':'启动旋翼','motion.stop':'停止旋翼','motion.speed':'展示转速','motion.pose':'姿态与云台','motion.pitch':'俯仰 Pitch','motion.roll':'横滚 Roll','motion.yaw':'航向 Yaw','motion.gimbalPitch':'云台俯仰','motion.gimbalYaw':'云台水平',
  'part.body':'机身','part.topCover':'顶盖','part.arms':'四机臂','part.rotors':'四旋翼','part.motors':'四电机','part.landingGear':'支撑杆','part.gimbal':'云台','part.camera':'摄像头','part.show':'显示 {part}','part.color':'{part}颜色',
  'status.online':'在线','status.mission':'任务','status.notice':'提示','status.warning':'告警','status.custom':'自定义','status.field':'状态场','status.hover':'悬浮','status.color':'状态颜色','status.speed':'扩散速度','status.range':'作用范围','status.intensity':'状态强度','status.lights':'状态灯','status.bloom':'光晕','status.lightIntensity':'灯光强度',
  'environment.solid':'纯色','environment.sky':'晴天','environment.rain':'雨天','environment.night':'夜间','environment.color':'纯色背景','environment.ground':'地景','environment.flightRoute':'城市循环航线（76 秒）','environment.flightFollow':'视角跟随','environment.brightness':'环境亮度','environment.groundIntensity':'地面强度','environment.rainAmount':'雨量','environment.fog':'雾感','environment.note':'雾感为 0 时完全关闭；环境切换不会重载模型。',
  'camera.perspective':'透视','camera.product45':'产品 45°','camera.top':'顶视','camera.front':'正视','camera.rear':'后视','camera.left':'左视','camera.right':'右视','camera.focal':'焦距（透视）','camera.distance':'距离（构图）','camera.height':'高度','camera.focus':'聚焦','camera.reset':'重置','camera.hint':'焦距改变透视压缩 · 距离改变机位与画面大小','camera.viewport':'交互三维视图',
  'export.imageTitle':'图片输出','export.format':'格式','export.size':'尺寸','export.custom':'自定义','export.width':'宽度','export.height':'高度','export.transparent':'透明背景','export.rain':'输出雨粒子','export.image':'导出图片','export.imageNote':'离屏渲染当前场景，不包含页面 UI','export.modelTitle':'模型输出','export.glb':'导出当前 GLB','export.glbNote':'保留当前模型材质、尺寸与可见对象','export.original':'下载原始 GLB ↗','export.rendering':'正在离屏渲染 {size}…','export.done':'输出完成 · {size} · {mb} MB','export.failed':'输出失败','export.writing':'正在写入当前 GLB…','export.glbDone':'导出完成 · {kb} KB','reset.all':'恢复 DEFAULT_DRONE_CONFIG','locale.label':'English','common.close':'关闭'
};
