import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {DroneController} from './drone/DroneController.js';
import {DroneModelAdapter} from './drone/DroneModelAdapter.js';
import {DEFAULT_DRONE_CONFIG,PART_DEFINITIONS,STATUS_PRESETS,cloneDroneConfig} from './drone/DroneAppearanceConfig.js';
import {applyDroneConfig} from './drone/DroneRuntimeConfig.js';
import {DroneSceneController} from './drone/scene/DroneSceneController.js';
import {DroneEnvironmentController,ENVIRONMENT_MODES} from './drone/scene/DroneEnvironmentController.js';
import {DroneCameraRig,CAMERA_PRESETS} from './drone/camera/DroneCameraRig.js';
import {DroneStatusField} from './drone/effects/DroneStatusField.js';
import {DroneHoverController} from './drone/effects/DroneHoverController.js';
import {DroneStatusController} from './drone/status/DroneStatusController.js';
import {createDronePackageConfig,downloadGLB,exportCurrentModelGLB} from './drone/export/DroneGLBExporter.js';
import {UIIcon} from './ui/UIIcon.js';
import {t,getLocale,setLocale,translatePage} from './i18n/index.js';
import {ModelSession,FULL_CAPABILITIES,GENERIC_CAPABILITIES} from './model/ModelSession.js';
import {FlightRouteController} from './environment/FlightRouteController.js';
import {ModelMappingDialog} from './model/ModelMappingDialog.js';
import {DroneRoleResolver} from './drone/profile/DroneRoleResolver.js';
import {loadCommunityRegistry,profileCapabilityKeys} from './model/CommunityModelLibrary.js';
import './viewer.css';

const poseSliders=[['pitch','motion.pitch',45],['roll','motion.roll',45],['yaw','motion.yaw',180],['gimbal-pitch','motion.gimbalPitch',45],['gimbal-yaw','motion.gimbalYaw',60]];
const cameraIcons={perspective:'perspective',product45:'navigation',top:'down',front:'up',rear:'down',left:'left',right:'right'},environmentIcons={solid:'swatch',sky:'sun',rain:'rain',night:'moon'};
const partRows=PART_DEFINITIONS.map(({key,color})=>`<div class="part-row"><strong data-i18n="part.${key}">${t(`part.${key}`)}</strong><input data-part-color="${key}" type="color" value="${color}"><code data-part-hex="${key}">${color.toUpperCase()}</code><label class="switch mini-switch"><input data-part-visible="${key}" type="checkbox" checked><i></i></label></div>`).join('');
const statusButtons=Object.entries(STATUS_PRESETS).map(([key,state])=>`<button data-state="${key}" aria-pressed="${key==='online'}"><i style="background:${state.color}"></i><span data-i18n="status.${key}">${t(`status.${key}`)}</span></button>`).join('');
const environmentButtons=Object.keys(ENVIRONMENT_MODES).map(key=>`<button data-environment="${key}" aria-pressed="${key==='solid'}">${UIIcon(environmentIcons[key])}<span data-i18n="environment.${key}">${t(`environment.${key}`)}</span></button>`).join('');

document.querySelector('#app').innerHTML=`
<header><strong>${UIIcon('drone',{size:20})}<span>AEROMETRIC <small data-i18n="app.version">${t('app.version')}</small></span></strong><button id="model-menu-toggle" class="model-entry"><span id="model-label">Quadrotor V3</span>⌄</button><button id="locale-toggle" class="locale-toggle" data-i18n="locale.label">${t('locale.label')}</button></header>
<div id="model-menu" class="model-menu" hidden><h3 data-i18n="model.preset">${t('model.preset')}</h3><button id="load-built-in" class="model-choice">● Quadrotor V3</button><h3 data-i18n="model.community">${t('model.community')}</h3><div id="community-models" class="community-models"><p data-i18n="model.libraryLoading">${t('model.libraryLoading')}</p></div><h3 data-i18n="model.local">${t('model.local')}</h3><button id="upload-trigger" class="model-choice">＋ <span data-i18n="model.upload">${t('model.upload')}</span></button><input id="model-file" type="file" accept=".glb,model/gltf-binary" hidden><p data-i18n="model.dropHint">${t('model.dropHint')}</p><hr><strong id="model-state"></strong><p id="model-metrics"></p><button id="configure-model" hidden data-i18n="model.configure">${t('model.configure')}</button><p id="model-message" role="status"></p></div>
<main><section class="stage"><div id="viewport" aria-label="${t('camera.viewport')}"></div><div id="drop-overlay" hidden>${UIIcon('download',{size:34})}<strong data-i18n="model.drop">${t('model.drop')}</strong></div><div id="loading" role="status" data-i18n="model.loading">${t('model.loading')}</div>
<div class="camera-dock"><nav>${Object.keys(CAMERA_PRESETS).map(key=>`<button data-view="${key}" class="${key==='perspective'?'selected':''}">${UIIcon(cameraIcons[key])}<span data-i18n="camera.${key}">${t(`camera.${key}`)}</span></button>`).join('')}</nav><div class="camera-tuning"><label><span data-i18n="camera.focal">${t('camera.focal')}</span> <output id="focal-value">55 mm</output><input id="focal" type="range" min="18" max="120" value="55"></label><label><span data-i18n="camera.distance">${t('camera.distance')}</span> <output id="distance-value">1.16 m</output><input id="distance" type="range" min="0.01" max="100" value="1.157" step="0.01"></label><label><span data-i18n="camera.height">${t('camera.height')}</span> <output id="camera-height-value">0.34 m</output><input id="camera-height" type="range" min="-100" max="100" value="0.34" step="0.01"></label><button id="focus-model">${UIIcon('focus')}<span data-i18n="camera.focus">${t('camera.focus')}</span></button><button id="reset-camera">${UIIcon('refresh')}<span data-i18n="camera.reset">${t('camera.reset')}</span></button></div></div><footer><span data-i18n="camera.hint">${t('camera.hint')}</span><span id="stats">—</span></footer></section>
<aside><h2><span data-i18n="app.console">${t('app.console')}</span> <em id="ready" data-i18n="app.loading">${t('app.loading')}</em></h2><fieldset id="controls" disabled>
<details id="drone-motion" name="control"><summary><span class="summary-label">${UIIcon('activity')}<span data-i18n="section.motion">${t('section.motion')}</span></span></summary><div class="panel-body"><h3 data-i18n="motion.rotor">${t('motion.rotor')}</h3><button id="spin" class="primary" aria-pressed="false">${UIIcon('play')}<span data-i18n="motion.start">${t('motion.start')}</span></button><label><span data-i18n="motion.speed">${t('motion.speed')}</span><output id="speed-value">12 rad/s</output><input id="speed" type="range" min="0" max="40" value="12"></label><h3><span data-i18n="motion.pose">${t('motion.pose')}</span> <small>°</small></h3>${poseSliders.map(([id,key,max])=>`<label><span data-i18n="${key}">${t(key)}</span><output id="${id}-value">0°</output><input id="${id}" type="range" min="${-max}" max="${max}" value="0"></label>`).join('')}</div></details>
<details id="drone-appearance" name="control"><summary><span class="summary-label">${UIIcon('palette')}<span data-i18n="section.appearance">${t('section.appearance')}</span></span></summary><div class="panel-body"><div class="part-list">${partRows}</div></div></details>
<details id="drone-status" name="control" open><summary><span class="summary-label">${UIIcon('radar')}<span data-i18n="section.status">${t('section.status')}</span></span><small id="status-name">${t('status.online')}</small></summary><div class="panel-body status-effects"><div class="states">${statusButtons}</div><div class="effect-switches"><label class="switch-card"><span>${UIIcon('radar')}<span data-i18n="status.field">${t('status.field')}</span></span><input id="status-field-visible" type="checkbox" checked><b></b></label><label class="switch-card"><span>${UIIcon('navigation')}<span data-i18n="status.hover">${t('status.hover')}</span></span><input id="hover-enabled" type="checkbox" checked><b></b></label></div><div class="effect-color"><strong data-i18n="status.color">${t('status.color')}</strong><input id="status-color" type="color" value="#3ba9ff"><code id="status-color-hex">#3BA9FF</code></div><label><span data-i18n="status.speed">${t('status.speed')}</span><output id="field-speed-value">0.55</output><input id="field-speed" type="range" min="0.2" max="2" value="0.55" step="0.05"></label><label><span data-i18n="status.range">${t('status.range')}</span><output id="field-range-value">1.80×</output><input id="field-range" type="range" min="1.2" max="2.4" value="1.8" step="0.05"></label><label><span data-i18n="status.intensity">${t('status.intensity')}</span><output id="field-intensity-value">0.40</output><input id="field-intensity" type="range" min="0" max="0.8" value="0.4" step="0.01"></label><div class="light-line"><label class="switch-card compact-switch"><span>${UIIcon('sun')}<span data-i18n="status.lights">${t('status.lights')}</span></span><input id="light-visible" type="checkbox" checked><b></b></label><label><span data-i18n="status.lightIntensity">${t('status.lightIntensity')}</span><output id="light-intensity-value">2.0</output><input id="light-intensity" type="range" min="0" max="4" value="2" step="0.1"></label></div></div></details>
<details name="control"><summary><span class="summary-label">${UIIcon('mountain')}<span data-i18n="section.environment">${t('section.environment')}</span></span></summary><div class="panel-body"><div class="mode-grid">${environmentButtons}</div><div class="effect-color"><strong data-i18n="environment.color">${t('environment.color')}</strong><input id="environment-color" type="color" value="#edf0f2"><code id="environment-color-hex">#EDF0F2</code></div><label class="switch-row"><span>${UIIcon('mountain')}<span data-i18n="environment.ground">${t('environment.ground')}</span></span><input id="ground-visible" type="checkbox" checked><b></b></label><label class="switch-row"><span>${UIIcon('navigation')}<span data-i18n="environment.flightRoute">${t('environment.flightRoute')}</span></span><input id="flight-route" type="checkbox"><b></b></label><label class="switch-row"><span>${UIIcon('focus')}<span data-i18n="environment.flightFollow">${t('environment.flightFollow')}</span></span><input id="flight-follow" type="checkbox" disabled><b></b></label>${[['environment-brightness','environment.brightness','1.00'],['ground-intensity','environment.groundIntensity','0.58'],['rain-amount','environment.rainAmount','0.65'],['fog','environment.fog','0.00']].map(([id,key,value])=>`<label id="${id==='rain-amount'?'rain-amount-row':id==='fog'?'fog-row':''}"><span data-i18n="${key}">${t(key)}</span><output id="${id}-value">${value}</output><input id="${id}" type="range" min="0" max="${id==='environment-brightness'?'1.5':'1'}" value="${value}" step="0.05"></label>`).join('')}<p class="note" data-i18n="environment.note">${t('environment.note')}</p></div></details>
<details name="control"><summary><span class="summary-label">${UIIcon('download')}<span data-i18n="section.export">${t('section.export')}</span></span></summary><div class="panel-body"><h3 data-i18n="export.imageTitle">${t('export.imageTitle')}</h3><div class="select-row"><label><span data-i18n="export.format">${t('export.format')}</span><select id="image-format"><option value="png">PNG</option><option value="jpg">JPG</option></select></label><label><span data-i18n="export.size">${t('export.size')}</span><select id="image-size"><option value="hd">1920×1080</option><option value="qhd">2560×1440</option><option value="uhd">3840×2160</option><option value="custom" data-i18n="export.custom">${t('export.custom')}</option></select></label></div><div id="custom-size" class="select-row" hidden><label><span data-i18n="export.width">${t('export.width')}</span><input id="image-width" type="number" min="64" max="8192" value="1920"></label><label><span data-i18n="export.height">${t('export.height')}</span><input id="image-height" type="number" min="64" max="8192" value="1080"></label></div><label class="switch-row"><span>${UIIcon('photo')}<span data-i18n="export.transparent">${t('export.transparent')}</span></span><input id="image-transparent" type="checkbox"><b></b></label><label class="switch-row"><span>${UIIcon('rain')}<span data-i18n="export.rain">${t('export.rain')}</span></span><input id="image-rain" type="checkbox" checked><b></b></label><button id="export-image" class="primary">${UIIcon('download')}<span data-i18n="export.image">${t('export.image')}</span></button><p id="image-status" class="export-status" data-i18n="export.imageNote">${t('export.imageNote')}</p><h3 data-i18n="export.modelTitle">${t('export.modelTitle')}</h3><button id="export-current" class="export-current">${UIIcon('box')}<span data-i18n="export.glb">${t('export.glb')}</span></button><p id="export-status" class="export-status" data-i18n="export.glbNote">${t('export.glbNote')}</p><a href="${import.meta.env.BASE_URL}models/drone_v3.glb" download data-i18n="export.original">${t('export.original')}</a></div></details>
<button id="reset" class="reset" data-i18n="reset.all">${t('reset.all')}</button></fieldset></aside></main><dialog id="mapping-dialog" class="mapping-dialog"><div class="mapping-head"><div><small>DRONE PROFILE</small><h2 data-i18n="mapping.title">${t('mapping.title')}</h2></div><button data-close aria-label="${t('common.close')}">×</button></div><p data-i18n="mapping.note">${t('mapping.note')}</p><div class="mapping-meta"><label><span>Profile ID</span><input name="profile-id"></label><label><span data-i18n="mapping.label">${t('mapping.label')}</span><input name="profile-label"></label><label><span data-i18n="mapping.forward">${t('mapping.forward')}</span><select name="forward-axis"><option>+Z</option><option>-Z</option><option>+X</option><option>-X</option></select></label></div><div class="mapping-roles"></div><p class="mapping-message" role="status"></p><footer><button data-auto data-i18n="mapping.auto">${t('mapping.auto')}</button><button data-save class="primary" data-i18n="mapping.save">${t('mapping.save')}</button></footer></dialog>`;

const viewport=document.querySelector('#viewport'),scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.005,50);
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=T.SRGBColorSpace;viewport.append(renderer.domElement);
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.55;pmrem.dispose();
const environmentController=new DroneEnvironmentController(scene),flightRoute=new FlightRouteController(environmentController.environmentRoot,{groundResolver:(x,z)=>environmentController.getGroundSurfaceYAt(x,z)}),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=.4;orbit.maxDistance=20;orbit.maxPolarAngle=Math.PI*.49;
const cameraRig=new DroneCameraRig(camera,orbit);let statusBloom=null;
let controller,adapter,droneScene,statusField,hoverController,statusController,currentSession,currentConfig=cloneDroneConfig(),elapsed=0,followInitialized=false;
const communityProfiles=new Map();
const followPoint=new T.Vector3(),followAnchor=new T.Vector3(),followDelta=new T.Vector3();
const mappingDialog=new ModelMappingDialog(document.querySelector('#mapping-dialog'),{translate:t,onApply:profile=>activateMappedProfile(profile)});

const val=id=>Number(document.getElementById(id).value);
function syncCameraUI(){const config=cameraRig.getConfig();currentConfig.camera=config;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===config.preset));for(const [id,value,suffix,digits] of [['focal',config.focalLength,' mm',0],['distance',config.distance,' m',2],['camera-height',config.height,' m',2]]){document.querySelector(`#${id}`).value=value;document.querySelector(`#${id}-value`).textContent=`${Number(value).toFixed(digits)}${suffix}`;}}
function setView(view){cameraRig.setPreset(view);syncCameraUI();}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));orbit.addEventListener('start',syncCameraUI);orbit.addEventListener('end',syncCameraUI);
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);statusBloom?.setSize(w,h);cameraRig.resize(w,h);}new ResizeObserver(resize).observe(viewport);resize();

function metrics(root,animations=[]){let meshes=0,triangles=0;const materials=new Set();root.traverse(object=>{if(!object.isMesh)return;meshes++;triangles+=(object.geometry.index?.count??object.geometry.attributes.position.count)/3;for(const material of Array.isArray(object.material)?object.material:[object.material])if(material)materials.add(material);object.castShadow=true;});return{meshes,triangles:Math.round(triangles),materials:materials.size,animations:animations.length};}
function makeDroneBundle(gltf,{sourceType='built-in',fileName='Quadrotor V3',objectUrl=null,profile=null}={}){const resolver=new DroneRoleResolver(gltf.scene,{profile}),declared=profile?.capabilities??resolver.capabilities(),capabilities=sourceType==='built-in'||!declared?FULL_CAPABILITIES:{...GENERIC_CAPABILITIES,...declared},nextScene=new DroneSceneController(gltf.scene,{profile,resolver}),nextController=new DroneController(nextScene.root,{poseRoot:nextScene.rotationRoot,profile}),nextAdapter=new DroneModelAdapter(nextScene.root,{profile}),nextField=new DroneStatusField(nextScene.effectRoot,nextScene.effectDiameter,DEFAULT_DRONE_CONFIG.status.statusField),nextHover=new DroneHoverController(nextScene.hoverRoot),nextStatus=new DroneStatusController({statusField:nextField,hover:nextHover,lights:nextAdapter.lights,rotor:nextController}),box=new T.Box3().setFromObject(nextScene.modelRoot,true);return{session:new ModelSession({sourceType,fileName,objectUrl,gltf,modelRoot:nextScene.modelRoot,sceneRoot:nextScene.root,capabilities,profile:sourceType==='compatible-imported'?(profile??'embedded'):null,boundingBox:box,metrics:{...metrics(nextScene.modelRoot,gltf.animations),size:box.getSize(new T.Vector3()),maxDimension:Math.max(...box.getSize(new T.Vector3()).toArray())}}),droneScene:nextScene,controller:nextController,adapter:nextAdapter,statusField:nextField,hoverController:nextHover,statusController:nextStatus};}
function importedBundle(gltf,{fileName='model.glb',profile=null}={}){const resolver=new DroneRoleResolver(gltf.scene,{profile}),fallback={root:['DRONE_ROOT'],'rotor.frontLeft':['ROTOR_FL'],'rotor.frontRight':['ROTOR_FR'],'rotor.rearLeft':['ROTOR_RL'],'rotor.rearRight':['ROTOR_RR'],'gimbal.pitch':['Gimbal_Pitch'],'gimbal.yaw':['Gimbal_Yaw'],camera:['Camera_Main']},required=['root','rotor.frontLeft','rotor.frontRight','rotor.rearLeft','rotor.rearRight','gimbal.pitch','gimbal.yaw','camera'].every(role=>resolver.one(role,{fallback:fallback[role]}));return required?makeDroneBundle(gltf,{sourceType:'compatible-imported',fileName,profile}):{session:ModelSession.inspectGLTF(gltf,{fileName})};}
function disposeCurrent(){flightRoute.bind(null);followInitialized=false;statusController?.dispose();adapter?.dispose();currentSession?.dispose();controller=adapter=droneScene=statusField=hoverController=statusController=currentSession=null;}
function syncCapabilities(){const c=currentSession?.capabilities??{};document.querySelector('#drone-motion').hidden=!(c.rotorControl||c.gimbalControl);document.querySelector('#drone-appearance').hidden=!(c.partColors||c.partVisibility);document.querySelector('#drone-status').hidden=!(c.statusField||c.statusLights);document.querySelector('#configure-model').hidden=!['generic-imported','profile-mapped'].includes(currentSession?.sourceType);document.querySelectorAll('[data-part-color]').forEach(input=>input.closest('.part-row').hidden=Boolean(adapter&&!adapter.hasPart(input.dataset.partColor)));}
function syncModelUI(message=''){if(!currentSession)return;const m=currentSession.metrics,stateKey=currentSession.sourceType==='built-in'?'model.builtIn':currentSession.sourceType==='compatible-imported'?'model.compatible':currentSession.sourceType==='profile-mapped'?'model.mapped':'model.generic';document.querySelector('#model-label').textContent=currentSession.fileName;document.querySelector('#model-state').textContent=t(stateKey);document.querySelector('#model-metrics').textContent=`${m.meshes} ${t('model.meshes')} · ${(m.triangles/1000).toFixed(1)}K ${t('model.triangles')} · ${m.materials} ${t('model.materials')} · ${m.animations} ${t('model.animations')}`;document.querySelector('#stats').textContent=`${(m.triangles/1000).toFixed(1)}k ${t('model.triangles')} · ${m.meshes} ${t('model.meshes')}`;document.querySelector('#model-message').textContent=message;}
async function commitBundle(bundle){scene.add(bundle.session.sceneRoot);disposeCurrent();currentSession=bundle.session;({droneScene=null,controller=null,adapter=null,statusField=null,hoverController=null,statusController=null}=bundle);flightRoute.bind(currentSession.sceneRoot);syncCapabilities();document.querySelector('#loading').hidden=true;const ready=document.querySelector('#ready');ready.dataset.i18n='app.ready';ready.textContent=t('app.ready');document.querySelector('#controls').disabled=false;if(controller)await applyDefaultConfig();else{cameraRig.focus(currentSession.sceneRoot);syncCameraUI();}syncModelUI();}
function activateMappedProfile(profile){controller=new DroneController(currentSession.modelRoot,{profile});adapter=new DroneModelAdapter(currentSession.modelRoot,{profile});currentSession.capabilities={...GENERIC_CAPABILITIES,...profile.capabilities,statusLights:false,statusField:false};for(const key of Object.keys(currentConfig.appearance))if(adapter.hasPart(key)){currentConfig.appearance[key].color=adapter.getPartColor(key)??currentConfig.appearance[key].color;currentConfig.appearance[key].visible=adapter.isPartVisible(key);syncPartRow(key);}syncCapabilities();syncSpin();syncModelUI(t('mapping.saved'));}
async function parseFile(file){if(!file?.name.toLowerCase().endsWith('.glb'))throw new Error(t('model.fileType'));const url=URL.createObjectURL(file);let gltf;try{gltf=await new GLTFLoader().loadAsync(url);}finally{URL.revokeObjectURL(url);}return importedBundle(gltf,{fileName:file.name});}
async function loadFile(file){const message=document.querySelector('#model-message');message.textContent=t('model.loading');try{const bundle=await parseFile(file);await commitBundle(bundle);const warnings=[];if(file.size>30*1024*1024)warnings.push(t('model.large'));if(bundle.session.metrics.maxDimension<.01||bundle.session.metrics.maxDimension>100)warnings.push(t('model.scale'));syncModelUI(warnings.join(' · ')||t('model.loaded'));}catch(error){console.error(error);message.textContent=t('model.unable');}}
async function loadBuiltIn(){document.querySelector('#model-message').textContent=t('model.loading');try{const gltf=await new GLTFLoader().loadAsync(`${import.meta.env.BASE_URL}models/drone_v3.glb`);await commitBundle(makeDroneBundle(gltf));}catch(error){console.error(error);document.querySelector('#model-message').textContent=t('model.unable');}}
async function communityProfile(entry){if(!entry.profileUrl)return null;if(!communityProfiles.has(entry.id))communityProfiles.set(entry.id,fetch(entry.profileUrl).then(response=>{if(!response.ok)throw new Error(`Profile request failed: ${response.status}`);return response.json();}));return communityProfiles.get(entry.id);}
async function loadCommunityModel(entry){const message=document.querySelector('#model-message');message.textContent=t('model.loading');try{const [gltf,profile]=await Promise.all([new GLTFLoader().loadAsync(entry.modelUrl),communityProfile(entry)]);await commitBundle(importedBundle(gltf,{fileName:`${entry.name}.glb`,profile}));modelMenu.hidden=true;syncModelUI(t('model.loaded'));}catch(error){console.error(error);message.textContent=t('model.unable');}}
async function loadCommunityModelLibrary(){const container=document.querySelector('#community-models');try{const entries=await loadCommunityRegistry(new URL(`${import.meta.env.BASE_URL}models/index.json`,location.href));container.replaceChildren();if(!entries.length){const empty=document.createElement('p');empty.dataset.i18n='model.libraryEmpty';empty.textContent=t('model.libraryEmpty');container.append(empty);return;}for(const entry of entries){const button=document.createElement('button'),image=document.createElement('img'),copy=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small');button.className='model-choice community-choice';image.src=entry.previewUrl;image.alt='';image.loading='lazy';name.textContent=entry.name;meta.textContent=`${entry.author} · L${entry.compatibility}`;copy.append(name,meta);button.append(image,copy);button.onclick=()=>loadCommunityModel(entry);container.append(button);communityProfile(entry).then(profile=>{const keys=profileCapabilityKeys(profile);if(keys.length)meta.textContent=`${entry.author} · ${keys.map(key=>t(`capability.${key}`)).join(' · ')}`;}).catch(()=>{});}}catch(error){console.error(error);container.replaceChildren();const unavailable=document.createElement('p');unavailable.dataset.i18n='model.libraryUnavailable';unavailable.textContent=t('model.libraryUnavailable');container.append(unavailable);}}

for(const id of [...poseSliders.map(s=>s[0]),'speed'])document.getElementById(id).oninput=event=>{if(!controller)return;document.getElementById(id+'-value').textContent=event.target.value+(id==='speed'?' rad/s':'°');if(id==='speed'){if(statusController)statusController.setManualRotorSpeed(val(id));else controller.speed=val(id);currentConfig.motion.rotorSpeed=val(id);}else if(id.startsWith('gimbal')){controller.setGimbal(val('gimbal-pitch'),val('gimbal-yaw'));currentConfig.motion.gimbalPitch=val('gimbal-pitch');currentConfig.motion.gimbalYaw=val('gimbal-yaw');}else{controller.setPose({pitch:val('pitch'),roll:val('roll'),yaw:val('yaw')});Object.assign(currentConfig.motion,{pitch:val('pitch'),roll:val('roll'),yaw:val('yaw')});}};
const spin=document.querySelector('#spin');function syncSpin(){if(!controller)return;spin.innerHTML=`${UIIcon(controller.running?'stop':'play')}<span data-i18n="motion.${controller.running?'stop':'start'}">${t(`motion.${controller.running?'stop':'start'}`)}</span>`;spin.setAttribute('aria-pressed',String(controller.running));}spin.onclick=()=>{if(!controller)return;if(statusController)statusController.setManualRotorRunning(!controller.running);else controller.running=!controller.running;currentConfig.motion.rotorRunning=controller.running;syncSpin();};

function syncPartRow(key){const config=currentConfig.appearance[key];document.querySelector(`[data-part-color="${key}"]`).value=config.color;document.querySelector(`[data-part-hex="${key}"]`).textContent=config.color.toUpperCase();document.querySelector(`[data-part-visible="${key}"]`).checked=config.visible;}
document.querySelectorAll('[data-part-color]').forEach(input=>input.oninput=e=>{if(!adapter)return;const key=e.target.dataset.partColor,color=e.target.value;currentConfig.appearance[key].color=color;adapter.setPartColor(key,color);syncPartRow(key);});document.querySelectorAll('[data-part-visible]').forEach(input=>input.onchange=()=>{if(!adapter)return;const key=input.dataset.partVisible,visible=input.checked;currentConfig.appearance[key].visible=visible;adapter.setPartVisible(key,visible);syncPartRow(key);});

function syncStatusUI(){if(!statusController)return;currentConfig.status=statusController.getConfig();const c=currentConfig.status;document.querySelector('#status-name').textContent=t(`status.${c.type}`);document.querySelectorAll('[data-state]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.state===c.type)));for(const [id,on] of [['status-field-visible',c.statusField.visible],['hover-enabled',c.hover.enabled],['light-visible',c.light.visible!==false]])document.querySelector(`#${id}`).checked=on;document.querySelector('#status-color').value=c.statusField.color;document.querySelector('#status-color-hex').textContent=c.statusField.color.toUpperCase();for(const [id,value,suffix=''] of [['field-speed',c.statusField.speed],['field-range',c.statusField.range,'×'],['field-intensity',c.statusField.intensity],['light-intensity',c.light.intensity]]){document.querySelector(`#${id}`).value=value;document.querySelector(`#${id}-value`).textContent=`${Number(value).toFixed(id==='light-intensity'?1:2)}${suffix}`;}syncSpin();}
const custom=update=>{statusController.setCustomStatus(update);syncStatusUI();};document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{statusController.setStatus(b.dataset.state);syncStatusUI();});document.querySelector('#status-color').oninput=e=>custom({color:e.target.value});document.querySelector('#status-field-visible').onchange=e=>{statusController.setStatusFieldVisible(e.target.checked);syncStatusUI();};document.querySelector('#hover-enabled').onchange=e=>{statusController.setHoverEnabled(e.target.checked);syncStatusUI();};document.querySelector('#light-visible').onchange=e=>{statusController.setLightVisible(e.target.checked);syncStatusUI();};for(const [id,key] of [['field-speed','speed'],['field-range','range'],['field-intensity','intensity']])document.querySelector(`#${id}`).oninput=e=>custom({statusField:{[key]:Number(e.target.value)}});document.querySelector('#light-intensity').oninput=e=>custom({light:{intensity:Number(e.target.value)}});

function syncEnvironmentUI(){const c=environmentController.getConfig();currentConfig.environment=c;document.querySelectorAll('[data-environment]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.environment===c.mode)));document.querySelector('#environment-color').value=c.color;document.querySelector('#environment-color-hex').textContent=c.color.toUpperCase();document.querySelector('#ground-visible').checked=c.groundVisible;document.querySelector('#flight-route').checked=Boolean(c.flightRoute);const follow=document.querySelector('#flight-follow');follow.checked=Boolean(c.cameraFollow);follow.disabled=!c.flightRoute;if(!c.cameraFollow)followInitialized=false;flightRoute.setEnabled(Boolean(c.flightRoute));for(const [id,value] of [['environment-brightness',c.brightness],['ground-intensity',c.groundIntensity],['rain-amount',c.rainAmount],['fog',c.fog]]){document.querySelector(`#${id}`).value=value;document.querySelector(`#${id}-value`).textContent=Number(value).toFixed(2);}document.querySelector('#rain-amount-row').hidden=c.mode!=='rain';document.querySelector('#fog-row').hidden=c.mode==='solid';}
async function updateEnvironment(update){await environmentController.applyConfig(update);syncEnvironmentUI();}
document.querySelectorAll('[data-environment]').forEach(b=>b.onclick=()=>updateEnvironment({mode:b.dataset.environment}));document.querySelector('#environment-color').oninput=e=>updateEnvironment({color:e.target.value});document.querySelector('#ground-visible').onchange=e=>updateEnvironment({groundVisible:e.target.checked});document.querySelector('#flight-route').onchange=e=>{const enabled=e.target.checked,c=environmentController.getConfig();if(enabled&&cameraRig.activeCamera!==camera)setView('perspective');followInitialized=false;updateEnvironment(enabled?{flightRoute:true,cameraFollow:true,groundVisible:true,mode:c.mode==='solid'?'sky':c.mode,fog:0}:{flightRoute:false,cameraFollow:false});};document.querySelector('#flight-follow').onchange=e=>{if(e.target.checked&&cameraRig.activeCamera!==camera)setView('perspective');followInitialized=false;updateEnvironment({cameraFollow:e.target.checked});};for(const [id,key] of [['environment-brightness','brightness'],['ground-intensity','groundIntensity'],['rain-amount','rainAmount'],['fog','fog']])document.querySelector(`#${id}`).oninput=e=>updateEnvironment({[key]:Number(e.target.value)});

for(const [id,method] of [['focal','setFocalLength'],['distance','setDistance'],['camera-height','setHeight']])document.querySelector(`#${id}`).oninput=e=>{if(cameraRig.activeCamera!==camera)setView('perspective');cameraRig[method](Number(e.target.value));syncCameraUI();};function focus(){if(currentSession)cameraRig.focus(currentSession.sceneRoot);syncCameraUI();}function resetCamera(){cameraRig.reset();if(currentSession?.sourceType!=='built-in')cameraRig.focus(currentSession.sceneRoot);syncCameraUI();}document.querySelector('#focus-model').onclick=focus;document.querySelector('#reset-camera').onclick=resetCamera;

const format=document.querySelector('#image-format'),sizePreset=document.querySelector('#image-size'),transparent=document.querySelector('#image-transparent');function syncImageOptions(){document.querySelector('#custom-size').hidden=sizePreset.value!=='custom';transparent.disabled=format.value==='jpg';if(format.value==='jpg')transparent.checked=false;}format.onchange=syncImageOptions;sizePreset.onchange=syncImageOptions;syncImageOptions();
document.querySelector('#export-image').onclick=async()=>{const button=document.querySelector('#export-image'),status=document.querySelector('#image-status');button.disabled=true;try{const {downloadImage,renderSceneImage,resolveImageSize}=await import('./drone/export/DroneImageExporter.js'),{width,height}=resolveImageSize(sizePreset.value,val('image-width'),val('image-height')),imageFormat=format.value,isTransparent=imageFormat==='png'&&transparent.checked;status.textContent=t('export.rendering',{size:`${width}×${height}`});const blob=await renderSceneImage({scene,camera:cameraRig.activeCamera,sourceRenderer:renderer,environment:environmentController,statusLights:adapter?.lights,width,height,format:imageFormat,transparent:isTransparent,includeRain:document.querySelector('#image-rain').checked});downloadImage(blob,`aerometric-${width}x${height}.${imageFormat}`);status.textContent=t('export.done',{size:`${width}×${height}`,mb:(blob.size/1024/1024).toFixed(1)});}catch(error){console.error(error);status.textContent=t('export.failed',{error:error.message});}finally{button.disabled=false;}};
const exportCurrent=document.querySelector('#export-current'),exportStatus=document.querySelector('#export-status');exportCurrent.onclick=async()=>{exportCurrent.disabled=true;exportStatus.textContent=t('export.writing');try{const glb=await exportCurrentModelGLB(currentSession.getExportRoot(),controller?{status:currentConfig.status}:{});downloadGLB(glb,`${currentSession.fileName.replace(/\.glb$/i,'')}-current.glb`);exportStatus.textContent=t('export.glbDone',{kb:(glb.byteLength/1024).toFixed(0)});}catch(error){console.error(error);exportStatus.textContent=t('export.failed',{error:error.message});}finally{exportCurrent.disabled=false;}};

async function applyDefaultConfig(){currentConfig=cloneDroneConfig();if(controller)currentConfig=applyDroneConfig({controller,adapter,statusController},DEFAULT_DRONE_CONFIG);await environmentController.applyConfig(currentConfig.environment);cameraRig.reset();if(!controller&&currentSession)cameraRig.focus(currentSession.sceneRoot);currentConfig.camera=cameraRig.getConfig();if(adapter)for(const key of Object.keys(currentConfig.appearance))syncPartRow(key);for(const id of ['speed','pitch','roll','yaw','gimbal-pitch','gimbal-yaw']){const key={'gimbal-pitch':'gimbalPitch','gimbal-yaw':'gimbalYaw'}[id]||id,value=id==='speed'?currentConfig.motion.rotorSpeed:currentConfig.motion[key];document.querySelector(`#${id}`).value=value;document.querySelector(`#${id}-value`).textContent=`${value}${id==='speed'?' rad/s':'°'}`;}syncStatusUI();syncEnvironmentUI();syncCameraUI();}document.querySelector('#reset').onclick=applyDefaultConfig;

const modelMenu=document.querySelector('#model-menu'),fileInput=document.querySelector('#model-file'),dropOverlay=document.querySelector('#drop-overlay');let communityLoaded=false;document.querySelector('#model-menu-toggle').onclick=()=>{modelMenu.hidden=!modelMenu.hidden;if(!modelMenu.hidden&&!communityLoaded){communityLoaded=true;loadCommunityModelLibrary();}};document.querySelector('#upload-trigger').onclick=()=>fileInput.click();fileInput.onchange=()=>{if(fileInput.files[0])loadFile(fileInput.files[0]);fileInput.value='';};document.querySelector('#load-built-in').onclick=()=>loadBuiltIn();document.querySelector('#configure-model').onclick=()=>{modelMenu.hidden=true;mappingDialog.open(currentSession);};
for(const eventName of ['dragenter','dragover'])viewport.addEventListener(eventName,event=>{event.preventDefault();dropOverlay.hidden=false;});for(const eventName of ['dragleave','drop'])viewport.addEventListener(eventName,event=>{event.preventDefault();dropOverlay.hidden=true;});viewport.addEventListener('drop',event=>{const file=[...event.dataTransfer.files].find(item=>item.name.toLowerCase().endsWith('.glb'));file?loadFile(file):document.querySelector('#model-message').textContent=t('model.fileType');});
function refreshLocale(){translatePage();syncSpin();syncStatusUI();syncModelUI();document.querySelector('#locale-toggle').textContent=t('locale.label');}document.querySelector('#locale-toggle').onclick=()=>{setLocale(getLocale()==='zh-CN'?'en-US':'zh-CN');refreshLocale();};
try{await loadBuiltIn();window.__DRONE_DEMO__={scene,renderer,environmentController,flightRoute,cameraRig,setEnvironment:updateEnvironment,loadFile,loadBuiltIn,get session(){return currentSession;},get controller(){return controller;},get adapter(){return adapter;},get droneScene(){return droneScene;},get model(){return currentSession?.modelRoot;},get exportRoot(){return currentSession?.getExportRoot();},exportCurrentGLB:()=>exportCurrentModelGLB(currentSession.getExportRoot(),controller?{status:currentConfig.status}:{}),getPackageConfig:()=>createDronePackageConfig(currentConfig),get config(){return currentConfig;},get activeCamera(){return cameraRig.activeCamera;}};}catch(error){console.error(error);document.querySelector('#loading').textContent=t('model.unable');document.querySelector('#ready').textContent=t('app.loadFailed');}

if(window.__DRONE_DEMO__)window.__DRONE_DEMO__.renderImage=async options=>{const {renderSceneImage}=await import('./drone/export/DroneImageExporter.js');return renderSceneImage({scene,camera:cameraRig.activeCamera,sourceRenderer:renderer,environment:environmentController,statusLights:adapter?.lights,...options});};
function updateFlightFollow(){if(!currentConfig.environment.cameraFollow||!flightRoute.enabled||cameraRig.activeCamera!==camera){followInitialized=false;return;}followPoint.copy(flightRoute.point);followPoint.y+=(currentSession?.metrics?.size?.y??.3)*.5;if(!followInitialized){followDelta.subVectors(followPoint,orbit.target);camera.position.add(followDelta);orbit.target.copy(followPoint);followAnchor.copy(followPoint);followInitialized=true;return;}followDelta.subVectors(followPoint,followAnchor);camera.position.add(followDelta);orbit.target.add(followDelta);followAnchor.copy(followPoint);}
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const delta=clock.getDelta();elapsed+=delta;controller?.update(delta);statusController?.update(delta,elapsed,cameraRig.activeCamera);flightRoute.update(delta);updateFlightFollow();environmentController.update(delta);orbit.update();if(statusBloom)statusBloom.render(cameraRig.activeCamera,adapter?.lights);else renderer.render(scene,cameraRig.activeCamera);});
function syncExportConfig(){currentConfig.export={format:format.value,size:sizePreset.value,width:val('image-width'),height:val('image-height'),transparent:format.value==='png'&&transparent.checked,includeRain:document.querySelector('#image-rain').checked};}
for(const id of ['image-format','image-size','image-width','image-height','image-transparent','image-rain'])document.querySelector(`#${id}`).addEventListener('change',syncExportConfig);syncExportConfig();
document.querySelector('#reset').addEventListener('click',()=>{format.value='png';sizePreset.value='hd';document.querySelector('#image-width').value=1920;document.querySelector('#image-height').value=1080;transparent.checked=false;document.querySelector('#image-rain').checked=true;syncImageOptions();syncExportConfig();});
const loadBloom=async()=>{try{const {StatusLightBloom}=await import('./drone/StatusLightBloom.js');statusBloom=new StatusLightBloom(renderer,scene,camera);resize();}catch(error){console.warn('Bloom unavailable',error);}};
if('requestIdleCallback'in globalThis)requestIdleCallback(loadBloom,{timeout:2000});else setTimeout(loadBloom,500);
